### ISSUE TITLE
an  problem about input

### ISSUE THREAD

**Issue by Charessss** [bcmi/DCI-VTON-Virtual-Try-On#26]
thanks for your great work！
when i was ran ‘sh test_VITON.sh’ ,
it displayed the error message ‘can not find the file path dataset/test_pairs.txt’.
After I putting the the test_pairs.txt and test directory from VITON-HD ,it displayed the error message ‘RuntimeError: running_mean should contain 16 elements not 23’ ! It seems that an usual problem about PyTorch input,however,I can not solve this problem.could you please give me some solutions or point out my other problems.Thanks very much.
![AB6E7758D35D314E20A4A2915250C261](https://github.com/bcmi/DCI-VTON-Virtual-Try-On/assets/105537560/db7548b4-b5eb-4134-acce-c89ffc446be5)
![584AFDE0B4A65EB451C4A76D38F6DD90](https://github.com/bcmi/DCI-VTON-Virtual-Try-On/assets/105537560/63f1ce6f-788a-4ab1-be88-46816baad1d9)
 the error message ‘RuntimeError: running_mean should contain 16 elements not 23’ 
![F25287A43CB57D689A10FCD9F47367A8](https://github.com/bcmi/DCI-VTON-Virtual-Try-On/assets/105537560/c6c08cd4-41eb-45ad-9d9c-7cf39b620376)

**Comment by Limbor** [comment]
Hi @Charessss It seems to be a problem with the number of input channels, and it should be the difference in the number of human parsing channels. Because the original number of labels is 20, but in the cp_dataset.py code we gave, it will map 20 categories to 13 categories, so the final input is 3+13=16 channels. You can check if there is a problem with this part of the conversion.
