### ISSUE TITLE
Tackle the Occlusion problem

### ISSUE THREAD

**Issue by nazapip** [bcmi/DCI-VTON-Virtual-Try-On#3]
Many of the virtual try on models have the problem of occlusion effect, in such cases images are not generated properly within the occluded region by the hands or some challenging pose. Does this model take care about that thing (paper results shows no such problem), how it can be tackled?

**Comment by Limbor** [comment]
Hi @nazapip. In fact, we do not do special handling for occlusion during the warping phase. In the diffusion model, since we are inpainting the entire upper body of the person, this problem can be well avoided with the powerful generation ability of the diffusion model. Thank you for your interest in our work.

**Comment by nazapip** [comment]
Hi @Limbor. Have you done training separately for the lower body garments and the dress part?

**Comment by Limbor** [comment]
@nazapip In our experiments, we use one model to train three categories of clothes simultaneously.
